development:
  adapter: mysql2
  database: foosleague
  username: root
  password:

test: &test
  adapter: mysql2
  database: foosleague_test
  username: root
  password:

production:
  adapter: mysql2
  database: foosleague
  username: root
  password:
